### PR TITLE
ci: migrate to fastify reusable workflow

### PR DESCRIPTION
**Pull request by Fdawgs**
adds support for node 18

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing :(

**Comment by Fdawgs** [comment]
I've looked through release notes and i can't find what changed in Node 17/18 to cause this issue, any ideas?

It's occurring in my own API repos when attempting to add Node 18 to the CI as well:
https://github.com/Fdawgs/ydh-sider-obfuscation-service/runs/6489000980?check_suite_focus=true#step:5:42

**Comment by mcollina** [comment]
You should update any reference of `localhost` to `127.0.0.1` and everything would work.

The reason this is failing is https://github.com/nodejs/node/pull/39987, which shipped as a semver-major change in node v17.

**Comment by Fdawgs** [comment]
Great thanks @mcollina! I'll get that updated in this repo.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
